services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: backend
    env_file:
      - .env
    ports:
      - "7777:7777"
    volumes:
      - .:/app
    depends_on:
      - db
    command: python run.py

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.flutter
    container_name: frontend
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
