// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOufMkxRE_vz_hOAD6qXlPUFDG1c97IUE',
    appId: '1:684880463559:web:d1c7e4472452aeed9b60e2',
    messagingSenderId: '684880463559',
    projectId: 'flutter-sarv-project',
    authDomain: 'flutter-sarv-project.firebaseapp.com',
    storageBucket: 'flutter-sarv-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUP_pwARUaqYwOXqFxtMZD5_w7fnH-cRk',
    appId: '1:684880463559:android:4d0dc6b6ac90f4819b60e2',
    messagingSenderId: '684880463559',
    projectId: 'flutter-sarv-project',
    storageBucket: 'flutter-sarv-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzigEbBVdJrDu1AeBoPm-Z2Y4fu27Vc74',
    appId: '1:684880463559:ios:9272120bf7364dce9b60e2',
    messagingSenderId: '684880463559',
    projectId: 'flutter-sarv-project',
    storageBucket: 'flutter-sarv-project.firebasestorage.app',
    iosBundleId: 'com.example.kpaErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOufMkxRE_vz_hOAD6qXlPUFDG1c97IUE',
    appId: '1:684880463559:web:adf497ba6c4ef4139b60e2',
    messagingSenderId: '684880463559',
    projectId: 'flutter-sarv-project',
    authDomain: 'flutter-sarv-project.firebaseapp.com',
    storageBucket: 'flutter-sarv-project.firebasestorage.app',
  );
}
